[package]
name = "iced_cross"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = [
    "crates/iced_cross_build",
    "examples/counter",
]

[workspace.dependencies]
iced = { path = "../../tmp/iced", features = ["tokio"] }
tauri = { path = "../../tmp/tauri/crates/tauri", features = ["no-webview"] }

[dependencies]
iced.workspace = true
tracing-subscriber = "0.3.22"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tauri = { workspace = true, optional = true }

[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-tracing = "2"

[features]
default = ["tauri-plugins"]
tauri-plugins = ["dep:tauri"]
hotpatch = ["iced/hot"]
